manifold:
    param_name: "problem_description_constraint"

    
state_validity_check:
    - collisions


collisions:
    type: "CollisionCheck"
    include_environment: true


RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1
    
RRTConnect:
    IntermediateStates: true
    Range: 0.9

state_space:
    floating_base_pos_min: [-0.5, -3.0, -0.5]
    floating_base_pos_max: [ 6.0,  3.0,  0.9]
    type: "Atlas"
    exploration: 0.9
    delta: 0.5
    epsilon: 0.5
    aplha: 0.39
    rho: 1.0
    lambda: 1500.0
    
control_space:
    duration: 0.1
    propagatorType: discrete