#### COMANPLUS_CONFIG ###
state_space:
    ee_number: 2
    bounds_x: [-1.0, 6.0]
    bounds_y: [-3.0, 3.0]
    end_effector: ["r_sole", "l_sole"]
    
control_space:
    step_size_max: 0.1
    min_control_duration: 1
    max_control_duration: 20   
    
propagator:
    type: "stepPropagator"
    duration: 0.3
    
state_validity_check:
    - collisions
    - stability

collisions:
    type: "CollisionCheck"
    include_environment: true
    
stability:
    type: "ConvexHull"
    links:
      - "l_foot_lower_left_link"
      - "l_foot_lower_right_link"
      - "l_foot_upper_left_link"
      - "l_foot_upper_right_link"
      - "r_foot_lower_left_link"
      - "r_foot_lower_right_link"
      - "r_foot_upper_left_link"
      - "r_foot_upper_right_link"

    stability_margin: 0.03
    
distance:
    type: "Distance"
    end_effector: ["r_sole", "l_sole"]
    max_x_distance: 0.5
    max_y_distance: 0.35
