### COMANPLUS_CONFIG ###
state_space:
    ee_number: 2
    bounds_x: [-1.0, 6.0]
    bounds_y: [-3.0, 3.0]
    end_effector: ["r_sole", "l_sole"]
    
control_space:
    step_size_max: 0.5
    min_control_duration: 1
    max_control_duration: 50
    
propagator:
    type: "stepPropagator"
    duration: 0.1
    
state_validity_check:
    - collisions


collisions:
    type: "CollisionCheck"
    include_environment: true
    
distance:
    type: "Distance"
    end_effector: ["r_sole", "l_sole"]
    max_x_distance: 0.5
    max_y_distance: 0.35
 
 
### CENTAURO_CONFIG ###
#state_space:
    #ee_number: 4
    #bounds_x: [-1.0, 6.0]
    #bounds_y: [-3.0, 3.0]
    #end_effector: ["wheel_1", "wheel_2", "wheel_3", "wheel_4"]
    
#control_space:
    #step_size_max: 0.1
    #min_control_duration: 1
    #max_control_duration: 50
    
#propagator:
    #type: "stepPropagator"
    #duration: 0.1
    
#state_validity_check:
    #- collisions

#collisions:
    #type: "CollisionCheck"
    #include_environment: true
    
#distance:
    #type: "Distance"
    #end_effector: ["wheel_1", "wheel_2", "wheel_3", "wheel_4"]
    #max_x_distance: 0.2
    #max_y_distance: 0.8
    #front_rear_x_distance: 0.5
    #left_right_y_distance: 0.2
    