manifold:
    param_name: "problem_description_constraint"

state_validity_check:
    - self_collision
    - stability
    - ground_collision

self_collision:
    type: "CollisionCheck"
    include_environment: true

stability:
    type: "CentroidalStatics"
    links: 
      - "l_sole"
      - "r_sole"
      - "l_ball_tip"
      - "r_ball_tip"
    friction_coefficient: 0.71
    eps: 5e-2
    x_lim_cop:
      - -0.025
      - 0.065
    y_lim_cop:
      - -0.025
      - 0.025

ground_collision:
    type: "GroundCollisionAvoidance"
    tolerance: -0.001
    links:
      - "l_sole"
      - "r_sole"
      - "l_ball_tip"
      - "r_ball_tip"
     

#stability:
#    type: "ConvexHull"
#    links:
#      - "l_foot_lower_left_link"
#      - "l_foot_lower_right_link"
#      - "l_foot_upper_left_link"
#      - "l_foot_upper_right_link"
#      - "r_foot_lower_left_link"
#      - "r_foot_lower_right_link"
#      - "r_foot_upper_left_link"
#      - "r_foot_upper_right_link"

#    stability_margin: 0.03

RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000
    
#RRTConnect:
    #Range: 1.0
    #IntermediateStates: true

state_space:
    floating_base_pos_min: [-1, -1, -1]
    floating_base_pos_max: [ 10,  10,  10]
    type: "Atlas"
    alpha: 0.5233
    rho: 0.1
    epsilon: 0.1
    exploration: 0.5
