manifold:
    param_name: "problem_description_constraint"

state_validity_check:
    - self_collision
    - stability

self_collision:
    type: "CollisionCheck"
    include_environment: true

stability:
    type: "CentroidalStatics"
    links: 
      - "l_sole"
      - "r_sole"
      - "l_ball_tip"
      - "r_ball_tip"
    friction_coefficient: 0.71
    eps: 5e-2
    x_lim_cop:
      - -0.05
      - 0.1
    y_lim_cop:
      - -0.05
      - 0.05

     

#stability:
#    type: "ConvexHull"
#    links:
#      - "l_foot_lower_left_link"
#      - "l_foot_lower_right_link"
#      - "l_foot_upper_left_link"
#      - "l_foot_upper_right_link"
#      - "r_foot_lower_left_link"
#      - "r_foot_lower_right_link"
#      - "r_foot_upper_left_link"
#      - "r_foot_upper_right_link"

#    stability_margin: 0.03

RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000

state_space:
    floating_base_pos_min: [-1, -1, -1]
    floating_base_pos_max: [ 1,  1,  1]
    type: "Atlas"
