manifold:
    param_name: "cartesian/problem_description_constraint"

state_validity_check:
    - self_collision
    - stability

self_collision:
    type: "CollisionChecker"
    include_environment: true

stability:
    type: "ConvexHull"
    links: ["link_1", "link_2", "link_3"]
    stability_margin: 0.03

RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000

state_space:
    floating_base_pos_min: [-1, -1, -1]
    floating_base_pos_max: [ 1,  1,  1]
    type: "Atlas"
