solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["l_sole", "r_sole", "l_ball_tip_d", "r_ball_tip_d"] #"l_ball_tip", "r_ball_tip"]
    #- ["Waist"]

constraints: ["JointLimits"]

JointLimits:
    type: "JointLimits"

l_sole:
    type: "Cartesian"
    distal_link: "l_sole"

r_sole:
    type: "Cartesian"
    distal_link: "r_sole"

Waist:
    type: "Cartesian"
    distal_link: "Waist"
    lambda: 0.1
    indices: [3, 4, 5]

Com:
    type: "Com"
    lambda: 0.1
    indices: [0, 1]

Postural:
    type: "Postural"
    lambda: 0.0

l_ball_tip:
    type: "Cartesian"
    distal_link: "l_ball_tip"
    lambda: 1.0
    indices: [0, 1, 2]

r_ball_tip:
    type: "Cartesian"
    distal_link: "r_ball_tip"
    lambda: 1.0
    indices: [0, 1, 2]

l_ball_tip_d:
    type: "Cartesian"
    distal_link: "l_ball_tip_d"
    lambda: 1.0
    indices: [0, 1, 2]

r_ball_tip_d:
    type: "Cartesian"
    distal_link: "r_ball_tip_d"
    lambda: 1.0
    indices: [0, 1, 2]

