solver_options:
    regularization: 1e-1
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot", "LeftHand", "RightHand"]
    - ["TorsoRPY"]
    - ["Postural"]
    
constraints: ["JointLimits"] #, "VelocityLimits"]

JointLimits:
    type: "JointLimits"

VelocityLimits:
    type: "VelocityLimits"

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"

Postural:
    type: "Postural"
    
LeftHand:
    type: "Cartesian"
    distal_link: "TCP_L"
    #indices: [0, 1, 2, 3, 4]
    #use_local_subtasks: "true"

RightHand:
    type: "Cartesian"
    distal_link: "TCP_R"
    #indices: [0, 1, 2, 3, 4]
    #use_local_subtasks: "true"

TorsoRPY:
    type: "Cartesian"
    distal_link: "torso"
    lambda: 1.0
    indices: [3,4]

