solver_options:
    regularization: 1e-2
    back_end: "qpoases"
    control_dt: 0.50 

stack:
    - ["LeftFoot", "RightFoot", "LeftHand", "RightHand"]
#    - ["TorsoRPY"]
#    - ["Postural"]
    
constraints: ["JointLimits"] #, "VelocityLimits"]

LeftFoot:
    type: "Cartesian"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    distal_link: "r_sole"

Postural:
    type: "Postural"
    lambda: 0.0
    
LeftHand:
    type: "Cartesian"
    distal_link: "TCP_L"
    lambda: 1.0

RightHand:
    type: "Cartesian"
    distal_link: "TCP_R"
    lambda: 1.0

TorsoRPY:
    type: "Cartesian"
    distal_link: "torso"
    lambda: 1.0
    indices: [3,4,5]

