solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot"]
    - ["Postural"]

constraints: ["JointLimits"]

JointLimits:
    type: "JointLimits"

LeftFoot:
    type: "Cartesian"
    base_link: "world"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    base_link: "world"
    distal_link: "r_sole"
    
Postural:
    type: "Postural"
    lambda: 1.
    
Com:
    type: "Com"
    indices: [0, 1]
    lambda: 0.1
    
Waist:
    type: "Cartesian"
    distal_link: "base_link"
    indices: [4]
    #, "Waist"]
    
    

    
    

