solver_options:
    regularization: 1e-2
    back_end: "qpoases"

stack:
    - ["LeftFoot", "RightFoot"]
    - ["Waist"]
    - ["Postural"]

constraints: ["JointLimits"]

JointLimits:
    type: "JointLimits"

LeftFoot:
    type: "Cartesian"
    base_link: "world"
    distal_link: "l_sole"

RightFoot:
    type: "Cartesian"
    base_link: "world"
    distal_link: "r_sole"

Postural:
    type: "Postural"
    lambda: 0.5
    
ComTask:
    type: "Com"
    weight: 10
    lambda: 0.05

ComXY:
    type: "Subtask"
    task: "ComTask"
    indices: [0, 1]

ComZ:
    type: "Subtask"
    task: "ComTask"
    indices: [2]
    
Waist:
    type: "Cartesian"
    distal_link: "base_link"
    indices: [4]
    


    
