ValidityCheck:
    - SelfCollision
    - Stability

SelfCollision:
    type: "CollisionChecker"
    include_environment: true

Stability:
    type: "ConvexHull"
    links: ["link_1", "link_2", "link_3"]
    stability_margin: 0.03

RRTstar:
    GoalBias: 0.1
    KNearest: true
    Range: 1000

StateSpace:
    type: "Atlas"
