solver_options:
    regularization: 1e-4
    back_end: "qpoases"

stack:
    #- ["ArmPosition", "ArmOrientation"]
    - ["ArmPosition"]
    #- ["Postural"]

    
constraints: ["JointLimits"]

JointLimits:
    type: "JointLimits"


ArmPosition:
    type: "Cartesian"
    distal_link: "TCP"
    base_link: "base_link"
    lambda: 0.1
    indices: [0,1,2]


