solver_options:
    regularization: 1e-4
    back_end: "odys"

stack:
    - ["ArmPosition"]

    
constraints: ["JointLimits", "VelocityLimits"]

ArmPosition:
    type: "Cartesian"
    distal_link: "TCP"
    base_link: "base_link"
    lambda: 0.1
    indices: [0,1,2]

ArmOrientation:
    type: "Cartesian"
    distal_link: "TCP"
    base_link: "base_link"
    lambda: 0.1
    indices: [3,4,5]
    use_body_jacobian: true
    

ArmEE:
    type: "Cartesian"
    distal_link: "teleop_link5"
    base_link: "base_link"
    lambda: 0.1
    indices: [0,1,2,3,4]

Postural:
    type: "Postural"
    lambda: 0.01
    
