#trajectorty space
string Joint=Joint
string Cartesian=Cartesian

string trajectory_space

#planner types
string BiTRRT=BiTRRT
string InformedRRTstar=InformedRRTstar
string LazyLBTRRT=LazyLBTRRT
string LazyRRT=LazyRRT
string LBTRRT=LBTRRT
string pRRT=pRRT
string RRT=RRT
string RRTConnect=RRTConnect
string RRTsharp=RRTsharp
string RRTstar=RRTstar
string RRTXstatic=RRTXstatic
string SORRTstar=SORRTstar
string TRRT=TRRT

string planner_type

int32 time

float32 interpolation_time

string[] base_links
string[] distal_links

---

cartesio_planning/CartesioPlannerStatus status
cartesio_planning/CartesianTrajectory[] cartesian_trajectory
trajectory_msgs/JointTrajectory joint_trajectory

